CREATE DATABASE IF NOT EXISTS floripa_check;
USE floripa_check;

CREATE TABLE IF NOT EXISTS praias (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(120) NOT NULL,
  bairro VARCHAR(120) NOT NULL,
  descricao TEXT NOT NULL,
  imagem_url VARCHAR(600) NOT NULL,
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS avaliacoes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  praia_id INT NOT NULL,
  usuario VARCHAR(120) NOT NULL,
  nota DECIMAL(2,1) NOT NULL,
  comentario TEXT NOT NULL,
  condicoes TEXT NOT NULL,
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (praia_id) REFERENCES praias(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS cadastros (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(120) NOT NULL,
  email VARCHAR(180) NOT NULL UNIQUE,
  senha_hash VARCHAR(255) NOT NULL,
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  atualizado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS logins (
  id INT AUTO_INCREMENT PRIMARY KEY,
  cadastro_id INT NULL,
  email VARCHAR(180) NOT NULL,
  sucesso BOOLEAN NOT NULL DEFAULT FALSE,
  ip VARCHAR(80),
  user_agent VARCHAR(255),
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (cadastro_id) REFERENCES cadastros(id) ON DELETE SET NULL
);




